### ISSUE TITLE
Exception occurs while downloading Orbit file

### ISSUE THREAD

**Issue by lumirinc** [scottstanie/sentineleof#19]
I am trying to download sentinel orbit file using eof command, however I am getting following exception and it fail to download orbit file.

[11/23 15:33:10] [INFO download.py] Downloading precise orbits for S1B on 2021-10-01
[11/23 15:33:10] [INFO download.py] Downloading precise orbits for S1B on 2021-10-13
Traceback (most recent call last):
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 1012, in _check_scihub_response
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://scihub.copernicus.eu/gnss/search?format=json&rows=100&start=0&q=beginPosition%3A%5B%222021-09-30T08%3A41%3A21Z%22+TO+%222021-10-02T08%3A41%3A21Z%22%5D+platformserialidentifier%3A%221B%22+producttype%3A%22AUX_POEORB%22

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gmtsar-user/.local/bin/eof", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/eof/cli.py", line 54, in cli
    download.main(
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/eof/download.py", line 384, in main
    return download_eofs(
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/eof/download.py", line 95, in download_eofs
    products = client.query_orbit(dt - ScihubGnssClient.T0,
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/eof/scihubclient.py", line 66, in query_orbit
    products = self._api.query(**query_params)
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 286, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 359, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 393, in _load_subquery
    self._check_scihub_response(response, query_string=query)
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 1058, in _check_scihub_response
    raise ServerError(msg, response)
sentinelsat.exceptions.ServerError: HTTP status 503 Service Unavailable: 
# 503 Service Unavailable

**Comment by scottstanie** [comment]
interesting, thanks for bringing that up. 
Is this an intermittent error? Or is it still occurring?

I ask because clicking on that link, and using the `gnssguest/gnssguest` username/password seems to work. I wonder if the scihub website had an issue for awhile. "503" generally is a problem from the server, rather than something wrong with the request you made: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503?retiredLocale=tr
`Common causes are a server that is down for maintenance or that is overloaded.`

**Comment by scottstanie** [comment]
It this happens regularly, it could be worth trying to build in a backup to the scihub website, maybe from the ASF-hosted orbit files.

**Comment by lumirinc** [comment]
Yesterday whole day it was giving the same error, however today it's working now. :-)

**Comment by scottstanie** [comment]
haha glad it's working now. 
I'll keep this open as a reminder- If it was down for a whole day, that indicates their API may fail again later, and we should have a backup.

**Comment by lumirinc** [comment]
Since yesterday sentineleof is not working. Seems API is down again.

**Comment by scottstanie** [comment]
Ok thanks for letting me know that this is semi-regular! i hadn't tried
orbit any recently. I'll bump it up on my mental list to fix at the next
chance

**Comment by lumirinc** [comment]
Here's the recent issue that I faced. None of the input products completely covers the requested time interval.

(base) lumir@lumir:~/InSAR/Indonesia/Mount_Sumeru_Volcano_Eruption_6Dec2021/asc/raw$ eof
[12/09 13:16:19] [INFO download.py] Downloading precise orbits for S1A on 2021-12-07
[12/09 13:16:19] [INFO download.py] Downloading precise orbits for S1A on 2021-11-25
Traceback (most recent call last):
  File "/home/lumir/anaconda3/bin/eof", line 8, in <module>
    sys.exit(cli())
  File "/home/lumir/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/lumir/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/lumir/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lumir/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/lumir/anaconda3/lib/python3.9/site-packages/eof/cli.py", line 54, in cli
    download.main(
  File "/home/lumir/anaconda3/lib/python3.9/site-packages/eof/download.py", line 384, in main
    return download_eofs(
  File "/home/lumir/anaconda3/lib/python3.9/site-packages/eof/download.py", line 110, in download_eofs
    result = (client._select_orbit(products, dt, dt + timedelta(minutes=1))
  File "/home/lumir/anaconda3/lib/python3.9/site-packages/eof/scihubclient.py", line 73, in _select_orbit
    product_id = lastval_cover(t0, t1, validity_info)
  File "/home/lumir/anaconda3/lib/python3.9/site-packages/eof/scihubclient.py", line 32, in lastval_cover
    raise ValidityError(
eof.scihubclient.ValidityError: none of the input products completely covers the requested time interval: [t0=2021-12-07 10:50:15, t1=2021-12-07 10:51:15]

**Comment by scottstanie** [comment]
hmm, I wonder if they just uploaded it now? Not sure what timezone your log time is in:

```python
$ eof --mission S1A --date 2021-12-07
Fetching archival status: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.53 products/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 560k/560k [00:01<00:00, 340kB/s]
MD5 checksumming: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 560k/560k [00:00<00:00, 282MB/s]
(mapping) scott:sentineleof$ lst
total 1144
-rw-r--r--   1 scott  staff   547K Dec  8 22:32 S1A_OPER_AUX_RESORB_OPOD_20211207T033054_V20211206T232132_20211207T023902.EOF
```

**Comment by scottstanie** [comment]
if you just ran that now, what's the name of the Sentinel .SAFE file that you used for me to check? I wonder if the SentinelSat client is unnecessarily strict in how it searches/decides what counts as fully valid.

**Comment by scottstanie** [comment]
If you're trying to process stuff ASAP and having continued problems, the fix I plan on making is to use this:
https://s1qc.asf.alaska.edu/aux_poeorb/

This has the precise orbits in an easy-to-parse page, or you can click on them if needed.

The one downside to this as the backup is you need to have a NASA account, as you do for all ASF downloads. This is something I wrote for a different application: https://github.com/scottstanie/sardem/blob/master/sardem/download.py#L236-L257 where it stores your username/password in a .netrc file if you haven't already done ie. I'll probably just copy/paste most of what i did before

**Comment by lumirinc** [comment]
> hmm, I wonder if they just uploaded it now? Not sure what timezone your log time is in:
> 
> ```python
> $ eof --mission S1A --date 2021-12-07
> Fetching archival status: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.53 products/s]
> Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 560k/560k [00:01<00:00, 340kB/s]
> MD5 checksumming: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 560k/560k [00:00<00:00, 282MB/s]
> (mapping) scott:sentineleof$ lst
> total 1144
> -rw-r--r--   1 scott  staff   547K Dec  8 22:32 S1A_OPER_AUX_RESORB_OPOD_20211207T033054_V20211206T232132_20211207T023902.EOF
> ```

I am accessing it from Korea.

**Comment by lumirinc** [comment]
> if you just ran that now, what's the name of the Sentinel .SAFE file that you used for me to check? I wonder if the SentinelSat client is unnecessarily strict in how it searches/decides what counts as fully valid.
Here's the list of sentinel-1 images that I am using for my work.

S1A_IW_SLC__1SDV_20211125T105016_20211125T105043_040726_04D543_F710.SAFE
S1A_IW_SLC__1SDV_20211207T105015_20211207T105043_040901_04DB5D_423E.SAFE

**Comment by scottstanie** [comment]
ok great, thanks for posting those, I'm getting the same error even now... so it's not something unrelated to it being slightly too new of an acquisition. I should be able to figure out where it's failing

**Comment by scottstanie** [comment]
Alright this appears to be something wrong with either the `sentinelsat` query tool, or (more likely), some kind of fault filtering of results from scihub API.
I can do a quick fix for the restituted orbits by just expanding our window, but i'll definitely also add the ASF backup 
(maybe even switching to that as the main form of orbit download)

**Comment by scottstanie** [comment]
@lumirinc thanks for all the reports of scihub being down, let me know if you see that again/if this new update doesn't give a working alternative.

I will need to note somewhere that the ASF download requires having the NASA username/password in a ~/.netrc file. I should possibly including the interactive adding of those credentials if it tries and fails to find that file
