### ISSUE TITLE
none of the input products completely covers the requested time interval

### ISSUE THREAD

**Issue by kanglcn** [scottstanie/sentineleof#29]
Hi,
I am using this software (version 0.6.3) to download orbit files. I have my slc raw zip file which is downloaded in ASF Vertex:
```
~/sc/Reeves/sentinel/descending/raw_data/slc ❯ ls error
S1B_IW_SLC__1SDV_20211217T141508_20211217T141535_030066_039705_A371.zip
```
and I run:
```
eof -p ./error --save-dir ./error
```
Then I got
```
[01/06 16:24:30] [INFO download.py] Downloading precise orbits for S1B on 2021-12-17
Traceback (most recent call last):
  File "/users/kangl/miniconda3/bin/eof", line 10, in <module>
    sys.exit(cli())
  File "/users/kangl/miniconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/users/kangl/miniconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/users/kangl/miniconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/kangl/miniconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/users/kangl/miniconda3/lib/python3.9/site-packages/eof/cli.py", line 55, in cli
    download.main(
  File "/users/kangl/miniconda3/lib/python3.9/site-packages/eof/download.py", line 239, in main
    return download_eofs(
  File "/users/kangl/miniconda3/lib/python3.9/site-packages/eof/download.py", line 81, in download_eofs
    query = client.query_orbit_by_dt(orbit_dts, missions, orbit_type=orbit_type)
  File "/users/kangl/miniconda3/lib/python3.9/site-packages/eof/scihubclient.py", line 132, in query_orbit_by_dt
    self._select_orbit(products, dt, dt + datetime.timedelta(minutes=1))
  File "/users/kangl/miniconda3/lib/python3.9/site-packages/eof/scihubclient.py", line 76, in _select_orbit
    product_id = lastval_cover(t0, t1, validity_info)
  File "/users/kangl/miniconda3/lib/python3.9/site-packages/eof/scihubclient.py", line 30, in lastval_cover
    raise ValidityError(
eof.scihubclient.ValidityError: none of the input products completely covers the requested time interval: [t0=2021-12-17 14:15:08, t1=2021-12-17 14:16:08]
```
I wonder this is because the orbit file does not exist on scihub's server.

**Comment by scottstanie** [comment]
Which version of this package do you have installed? Just checking since this is the same error as what was reported in #19 , and it's hopefully fixed in the most recent update.

Does this still happen when you do `pip install --upgrade sentineleof`? (or conda upgrade if you used conda)?

**Comment by scottstanie** [comment]
sorry I missed that you opened with your software version haha. 

I'm getting the same error as you are. I'll take a look and see what I find

**Comment by scottstanie** [comment]
Yes you are correct that the overlapping precise orbit is 1 day away from getting uploaded... but not I'm wondering why it's almost finding it and failing, and not falling back to the restituted orbits.

I'm not sure if this would be what you want for your processing, but I do think this shouldn't fail as it's doing

**Comment by scottstanie** [comment]
okay just adding a catch of this error moves it from precise to ResOrbs. lemme know if you have any more troubles!

**Comment by kanglcn** [comment]
I see your point. Taking all situations into consideration is hard when dealing with such a critical point. For me, I don't really need the newest data so this is not a big problem hhh.
 Thank you again for your so efficient reply!
