### ISSUE TITLE
Access token creation failed.

### ISSUE THREAD

**Issue by BianSun** [scottstanie/sentineleof#56]
Traceback (most recent call last):
  File "/home/wanchao/anaconda3/envs/isce2_env/lib/python3.8/site-packages/eof/dataspace_client.py", line 301, in get_access_token
    r.raise_for_status()
  File "/home/wanchao/anaconda3/envs/isce2_env/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wanchao/anaconda3/envs/isce2_env/bin/eof", line 10, in <module>
    sys.exit(cli())
  File "/home/wanchao/anaconda3/envs/isce2_env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/wanchao/anaconda3/envs/isce2_env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/wanchao/anaconda3/envs/isce2_env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wanchao/anaconda3/envs/isce2_env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/wanchao/anaconda3/envs/isce2_env/lib/python3.8/site-packages/eof/cli.py", line 134, in cli
    download.main(
  File "/home/wanchao/anaconda3/envs/isce2_env/lib/python3.8/site-packages/eof/download.py", line 246, in main
    return download_eofs(
  File "/home/wanchao/anaconda3/envs/isce2_env/lib/python3.8/site-packages/eof/download.py", line 107, in download_eofs
    results = client.download_all(
  File "/home/wanchao/anaconda3/envs/isce2_env/lib/python3.8/site-packages/eof/dataspace_client.py", line 175, in download_all
    return download_all(
  File "/home/wanchao/anaconda3/envs/isce2_env/lib/python3.8/site-packages/eof/dataspace_client.py", line 407, in download_all
    access_token = get_access_token(username, password)
  File "/home/wanchao/anaconda3/envs/isce2_env/lib/python3.8/site-packages/eof/dataspace_client.py", line 303, in get_access_token
    raise RuntimeError(f"Access token creation failed. Reason: {str(err)}")
RuntimeError: Access token creation failed. Reason: 400 Client Error: Bad Request for url: https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token                      Excuse me, I am rather confused about this point. How can I solve it?

**Comment by scottstanie** [comment]
Hi @BianSun , did this resolve itself for you? For what it's work, I also got an internal server error when I clicked that token URL:
<img width="668" alt="image" src="https://github.com/scottstanie/sentineleof/assets/8291800/31874e40-614a-468f-97e3-001e2181995d">
so perhaps copernicus is having a transient issue
