### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by AdnanKaisarKhan** [scottstanie/sentineleof#60]
[02/28 12:35:21] [INFO download.py] Downloading precise orbits for S1A on 2022-05-30
[02/28 12:35:21] [INFO download.py] Downloading precise orbits for S1A on 2022-05-18
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1017, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fb8546cc790>, 'Connection to scihub.copernicus.eu timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='scihub.copernicus.eu', port=443): Max retries exceeded with url: /gnss/search?format=json&rows=100&start=0&q=platformserialidentifier%3A%22S1A%22+producttype%3A%22AUX_POEORB%22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb8546cc790>, 'Connection to scihub.copernicus.eu timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adnan/.local/bin/eof", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/adnan/.local/lib/python3.10/site-packages/eof/cli.py", line 62, in cli
    download.main(
  File "/home/adnan/.local/lib/python3.10/site-packages/eof/download.py", line 266, in main
    return download_eofs(
  File "/home/adnan/.local/lib/python3.10/site-packages/eof/download.py", line 84, in download_eofs
    if client.server_is_up() and not force_asf:
  File "/home/adnan/.local/lib/python3.10/site-packages/eof/scihubclient.py", line 206, in server_is_up
    self._api.query(producttype="AUX_POEORB", platformserialidentifier="S1A")
  File "/home/adnan/.local/lib/python3.10/site-packages/sentinelsat/sentinel.py", line 282, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/home/adnan/.local/lib/python3.10/site-packages/sentinelsat/sentinel.py", line 355, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/home/adnan/.local/lib/python3.10/site-packages/sentinelsat/sentinel.py", line 388, in _load_subquery
    response = self.session.get(url, params={"q": query.encode("latin1")})
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 557, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='scihub.copernicus.eu', port=443): Max retries exceeded with url: /gnss/search?format=json&rows=100&start=0&q=platformserialidentifier%3A%22S1A%22+producttype%3A%22AUX_POEORB%22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb8546cc790>, 'Connection to scihub.copernicus.eu timed out. (connect timeout=None)'))

**Comment by scottstanie** [comment]
What is the version you're using? 
```
$ python -c 'import eof; print(eof.__version__)'
0.9.5
```

**Comment by scottstanie** [comment]
Oh i see you have `scihub` in your traceback error. You need to update the version as outlined in the README: https://github.com/scottstanie/sentineleof?tab=readme-ov-file#update-2023-10-31-changes-to-sentinel-1-orbit-files-source
